language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
before_script:
  - "pep8 --ignore=E501 escherauth"
install:
  - pip install -r requirements.txt
script: nosetests
deploy:
  - provider: pypi
    distributions: sdist bdist_egg
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    on:
      tags: true
      python: "2.7"
  - provider: pypi
    distributions: bdist_egg
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    on:
      tags: true
      python: "3.3"
  - provider: pypi
    distributions: bdist_egg
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
    on:
      tags: true
      python: "3.4"
